### ISSUE TITLE
About Swift Functors, Applicatives, and Monads in Pictures article.

### ISSUE THREAD

**Issue by dakeshi** [mokagio/mokacoding#8]
Hi @mokagio 
I read your great article about [Monads with Swift](http://www.mokacoding.com/blog/functor-applicative-monads-in-pictures/) in your blog.
It's very helpful for me to understand Monads once again. 👍 
Thank you. ❤️ 

But, during testing your example codes, I found out that your map function code would not be correct.

Your map implementation is:

``` swift
func map<U>(f: T -> U) -> U? {
  switch self {
  case .Some(let x): return f(x)
  case .None: return .None
}
```

I think `return f(x)` need to be `return .Some(f(x))`.

And the below code is the [Optional.swift in apple's swift repo](https://github.com/apple/swift/blob/master/stdlib/public/core/Optional.swift):

``` swift
  public func map<U>(_ f: @noescape (Wrapped) throws -> U) rethrows -> U? {
    switch self {
    case .some(let y):
      return .some(try f(y))
    case .none:
      return .none
    }
  }
```

I'd like to make a comment in your blog but it didn't work your comment system under this article.
So I open a issue here. 

Thank you again to make this wonderful article.

**Comment by mokagio** [comment]
Hey @dakeshi, thank you for your kind words, and for taking the time to leave a comment. Please forgive me for taking so long to reply to you.

> I think `return f(x)` need to be `return .some(f(x))`.

Both syntax are build fine and are, _as far as I'm concerned_, correct.

The option with `.some(f(x))` that you saw in the Apple samples is simply more _explicit_.

My understanding is that the compiler is able to automatically wrap a value of type `U` into the optional when returned from a function with signature `-> U?`.
